### ISSUE TITLE
problem with build of devel docker image

### ISSUE THREAD

**Issue by geraldstanje** [tensorflow/serving#1554]
Please go to Stack Overflow for help and support:

https://stackoverflow.com/questions/tagged/tensorflow-serving

If you open a GitHub issue, here is our policy:

1. It must be a bug, a feature request, or a significant problem with
   documentation (for small docs fixes please send a PR instead).
2. The form below must be filled out.

**Here's why we have that policy**: TensorFlow developers respond to issues.
We want to focus on work that benefits the whole community, e.g., fixing bugs
and adding features. Support only helps individuals. GitHub also notifies
thousands of people when issues are filed. We want them to see you communicating
an interesting problem, rather than being redirected to Stack Overflow.

-----------------------
## Feature Request
If this is a feature request, please fill out the following form in full:

### Describe the problem the feature is intended to solve
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

### Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've
considered.

## Bug Report
If this is a bug report, please fill out the following form in full:

here the error, i also tried it without setting --jobs=1:
```
Sending build context to Docker daemon  10.41MB
Step 1/24 : FROM ubuntu:18.04 as base_build
18.04: Pulling from library/ubuntu
Digest: sha256:8d31dad0c58f552e890d68bbfb735588b6b820a46e459672d96e585871acc110
Status: Image is up to date for ubuntu:18.04
 ---> ccc6e87d482b
Step 2/24 : ARG TF_SERVING_VERSION_GIT_BRANCH=master
 ---> Using cache
 ---> 3df1b5681d31
Step 3/24 : ARG TF_SERVING_VERSION_GIT_COMMIT=head
 ---> Using cache
 ---> e1d592ee8bc6
Step 4/24 : LABEL maintainer=gvasudevan@google.com
 ---> Using cache
 ---> 15b48750c78e
Step 5/24 : LABEL tensorflow_serving_github_branchtag=${TF_SERVING_VERSION_GIT_BRANCH}
 ---> Using cache
 ---> c9d90ce54092
Step 6/24 : LABEL tensorflow_serving_github_commit=${TF_SERVING_VERSION_GIT_COMMIT}
 ---> Using cache
 ---> d5f6c04b6e6b
Step 7/24 : RUN apt-get update && apt-get install -y --no-install-recommends         automake         build-essential         ca-certificates         curl         git         libcurl3-dev         libfreetype6-dev         libpng-dev         libtool         libzmq3-dev         mlocate         openjdk-8-jdk        openjdk-8-jre-headless         pkg-config         python-dev         software-properties-common         swig         unzip         wget         zip         zlib1g-dev         &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 46e256e112f3
Step 8/24 : RUN curl -fSsL -O https://bootstrap.pypa.io/get-pip.py &&     python get-pip.py &&     rm get-pip.py
 ---> Using cache
 ---> c3d5d9054165
Step 9/24 : RUN pip --no-cache-dir install     future>=0.17.1     grpcio     h5py     keras_applications>=1.0.8     keras_preprocessing>=1.1.0     mock     numpy     requests
 ---> Using cache
 ---> 90d8aefa80c5
Step 10/24 : ENV BAZEL_VERSION 0.24.1
 ---> Using cache
 ---> 7f8ed2e1a161
Step 11/24 : WORKDIR /
 ---> Using cache
 ---> 949cc655d29b
Step 12/24 : RUN mkdir /bazel &&     cd /bazel &&     curl -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36" -fSsL -O https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-installer-linux-x86_64.sh &&     curl -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36" -fSsL -o /bazel/LICENSE.txt https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE &&     chmod +x bazel-*.sh &&     ./bazel-$BAZEL_VERSION-installer-linux-x86_64.sh &&     cd / &&     rm -f /bazel/bazel-$BAZEL_VERSION-installer-linux-x86_64.sh
 ---> Using cache
 ---> 9d569af8fa2a
Step 13/24 : WORKDIR /tensorflow-serving
 ---> Using cache
 ---> 8edd5b832654
Step 14/24 : RUN git clone --branch=${TF_SERVING_VERSION_GIT_BRANCH} https://github.com/tensorflow/serving . &&     git remote add upstream https://github.com/tensorflow/serving.git &&     if [ "${TF_SERVING_VERSION_GIT_COMMIT}" != "head" ]; then git checkout ${TF_SERVING_VERSION_GIT_COMMIT} ; fi
 ---> Using cache
 ---> e4e4b6954dae
Step 15/24 : FROM base_build as binary_build
 ---> e4e4b6954dae
Step 16/24 : ARG TF_SERVING_BUILD_OPTIONS="--config=nativeopt"
 ---> Using cache
 ---> 79670575e466
Step 17/24 : RUN echo "Building with build options: ${TF_SERVING_BUILD_OPTIONS}"
 ---> Running in 094a5c43d0a3
Building with build options: --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-msse4.1 --copt=-msse4.2 --jobs=1 --local_resources=8192,2.0,1.0
Removing intermediate container 094a5c43d0a3
 ---> 24411afa50b0
Step 18/24 : ARG TF_SERVING_BAZEL_OPTIONS=""
 ---> Running in c6c5f6ee5d58
Removing intermediate container c6c5f6ee5d58
 ---> 61eda7e8245e
Step 19/24 : RUN echo "Building with Bazel options: ${TF_SERVING_BAZEL_OPTIONS}"
 ---> Running in eb1c98d6c8c4
Building with Bazel options: 
Removing intermediate container eb1c98d6c8c4
 ---> 1b9208cb2d1e
Step 20/24 : RUN bazel build --color=yes --curses=yes     ${TF_SERVING_BAZEL_OPTIONS}     --verbose_failures     --output_filter=DONT_MATCH_ANYTHING     ${TF_SERVING_BUILD_OPTIONS}     tensorflow_serving/model_servers:tensorflow_model_server &&     cp bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server     /usr/local/bin/
 ---> Running in a3900fbc9909
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analysed target //tensorflow_serving/model_servers:tensorflow_model_server (192 packages loaded, 15036 targets configured).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/org_tensorflow/tensorflow/core/kernels/BUILD:3828:1: C++ compilation of rule '@org_tensorflow//tensorflow/core/kernels:argmax_op' failed (Exit 4): gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/execroot/tf_serving && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/core/kernels/_objs/argmax_op/argmax_op.d '-frandom-seed=bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/core/kernels/_objs/argmax_op/argmax_op.o' -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DEIGEN_HAS_TYPE_TRAITS=0' -DTF_USE_SNAPPY -DCURL_STATICLIB -DPLATFORM_LINUX -DENABLE_CURL_CLIENT -DENABLE_NO_ENCRYPTION -iquote external/org_tensorflow -iquote bazel-out/k8-opt/genfiles/external/org_tensorflow -iquote bazel-out/k8-opt/bin/external/org_tensorflow -iquote external/com_google_absl -iquote bazel-out/k8-opt/genfiles/external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -iquote external/nsync -iquote bazel-out/k8-opt/genfiles/external/nsync -iquote bazel-out/k8-opt/bin/external/nsync -iquote external/eigen_archive -iquote bazel-out/k8-opt/genfiles/external/eigen_archive -iquote bazel-out/k8-opt/bin/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/k8-opt/genfiles/external/local_config_sycl -iquote bazel-out/k8-opt/bin/external/local_config_sycl -iquote external/com_googlesource_code_re2 -iquote bazel-out/k8-opt/genfiles/external/com_googlesource_code_re2 -iquote bazel-out/k8-opt/bin/external/com_googlesource_code_re2 -iquote external/gif -iquote bazel-out/k8-opt/genfiles/external/gif -iquote bazel-out/k8-opt/bin/external/gif -iquote external/libjpeg_turbo -iquote bazel-out/k8-opt/genfiles/external/libjpeg_turbo -iquote bazel-out/k8-opt/bin/external/libjpeg_turbo -iquote external/com_google_protobuf -iquote bazel-out/k8-opt/genfiles/external/com_google_protobuf -iquote bazel-out/k8-opt/bin/external/com_google_protobuf -iquote external/zlib_archive -iquote bazel-out/k8-opt/genfiles/external/zlib_archive -iquote bazel-out/k8-opt/bin/external/zlib_archive -iquote external/farmhash_archive -iquote bazel-out/k8-opt/genfiles/external/farmhash_archive -iquote bazel-out/k8-opt/bin/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/k8-opt/genfiles/external/fft2d -iquote bazel-out/k8-opt/bin/external/fft2d -iquote external/highwayhash -iquote bazel-out/k8-opt/genfiles/external/highwayhash -iquote bazel-out/k8-opt/bin/external/highwayhash -iquote external/double_conversion -iquote bazel-out/k8-opt/genfiles/external/double_conversion -iquote bazel-out/k8-opt/bin/external/double_conversion -iquote external/snappy -iquote bazel-out/k8-opt/genfiles/external/snappy -iquote bazel-out/k8-opt/bin/external/snappy -iquote external/hwloc -iquote bazel-out/k8-opt/genfiles/external/hwloc -iquote bazel-out/k8-opt/bin/external/hwloc -iquote external/curl -iquote bazel-out/k8-opt/genfiles/external/curl -iquote bazel-out/k8-opt/bin/external/curl -iquote external/boringssl -iquote bazel-out/k8-opt/genfiles/external/boringssl -iquote bazel-out/k8-opt/bin/external/boringssl -iquote external/jsoncpp_git -iquote bazel-out/k8-opt/genfiles/external/jsoncpp_git -iquote bazel-out/k8-opt/bin/external/jsoncpp_git -iquote external/aws -iquote bazel-out/k8-opt/genfiles/external/aws -iquote bazel-out/k8-opt/bin/external/aws -isystem external/nsync/public -isystem bazel-out/k8-opt/genfiles/external/nsync/public -isystem bazel-out/k8-opt/bin/external/nsync/public -isystem external/eigen_archive -isystem bazel-out/k8-opt/genfiles/external/eigen_archive -isystem bazel-out/k8-opt/bin/external/eigen_archive -isystem external/gif -isystem bazel-out/k8-opt/genfiles/external/gif -isystem bazel-out/k8-opt/bin/external/gif -isystem external/com_google_protobuf/src -isystem bazel-out/k8-opt/genfiles/external/com_google_protobuf/src -isystem bazel-out/k8-opt/bin/external/com_google_protobuf/src -isystem external/zlib_archive -isystem bazel-out/k8-opt/genfiles/external/zlib_archive -isystem bazel-out/k8-opt/bin/external/zlib_archive -isystem external/farmhash_archive/src -isystem bazel-out/k8-opt/genfiles/external/farmhash_archive/src -isystem bazel-out/k8-opt/bin/external/farmhash_archive/src -isystem external/double_conversion -isystem bazel-out/k8-opt/genfiles/external/double_conversion -isystem bazel-out/k8-opt/bin/external/double_conversion -isystem external/hwloc/hwloc -isystem bazel-out/k8-opt/genfiles/external/hwloc/hwloc -isystem bazel-out/k8-opt/bin/external/hwloc/hwloc -isystem external/hwloc/include -isystem bazel-out/k8-opt/genfiles/external/hwloc/include -isystem bazel-out/k8-opt/bin/external/hwloc/include -isystem external/curl/include -isystem bazel-out/k8-opt/genfiles/external/curl/include -isystem bazel-out/k8-opt/bin/external/curl/include -isystem external/boringssl/src/include -isystem bazel-out/k8-opt/genfiles/external/boringssl/src/include -isystem bazel-out/k8-opt/bin/external/boringssl/src/include -isystem external/jsoncpp_git/include -isystem bazel-out/k8-opt/genfiles/external/jsoncpp_git/include -isystem bazel-out/k8-opt/bin/external/jsoncpp_git/include -isystem external/aws/aws-cpp-sdk-core/include -isystem bazel-out/k8-opt/genfiles/external/aws/aws-cpp-sdk-core/include -isystem bazel-out/k8-opt/bin/external/aws/aws-cpp-sdk-core/include -isystem external/aws/aws-cpp-sdk-s3/include -isystem bazel-out/k8-opt/genfiles/external/aws/aws-cpp-sdk-s3/include -isystem bazel-out/k8-opt/bin/external/aws/aws-cpp-sdk-s3/include -mavx -mavx2 -mfma -msse4.1 -msse4.2 '-std=c++14' '-D_GLIBCXX_USE_CXX11_ABI=0' -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare '-ftemplate-depth=900' -fno-exceptions -msse3 -DTENSORFLOW_MONOLITHIC_BUILD -pthread -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/org_tensorflow/tensorflow/core/kernels/argmax_op.cc -o bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/core/kernels/_objs/argmax_op/argmax_op.o)
Execution platform: @bazel_tools//platforms:host_platform
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Target //tensorflow_serving/model_servers:tensorflow_model_server failed to build
INFO: Elapsed time: 5271.647s, Critical Path: 1591.11s
INFO: 3234 processes: 3234 local.
FAILED: Build did NOT complete successfully
The command '/bin/sh -c bazel build --color=yes --curses=yes     ${TF_SERVING_BAZEL_OPTIONS}     --verbose_failures     --output_filter=DONT_MATCH_ANYTHING     ${TF_SERVING_BUILD_OPTIONS}     tensorflow_serving/model_servers:tensorflow_model_server &&     cp bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server     /usr/local/bin/' returned a non-zero code: 1
Sending build context to Docker daemon  10.41MB
Step 1/18 : ARG TF_SERVING_VERSION=latest
Step 2/18 : ARG TF_SERVING_BUILD_IMAGE=tensorflow/serving:${TF_SERVING_VERSION}-devel
Step 3/18 : FROM ${TF_SERVING_BUILD_IMAGE} as build_image
pull access denied for geri/tensorflow-serving-devel, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

here another try with ```TF_SERVING_BUILD_OPTIONS="--cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-msse4.1 --copt=-msse4.2 --local_resources=8192,2.0,1.0"```
```
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analysed target //tensorflow_serving/model_servers:tensorflow_model_server (192 packages loaded, 15036 targets configured).
INFO: Found 1 target...
[3,158 / 4,671] 8 actions, 2 running
    @org_tensorflow//tensorflow/core/kernels:cwise_op; 966s local
    @org_tensorflow//tensorflow/core/kernels:cwise_op; 953s local
    [Sched] @org_tensorflow//tensorflow/core/kernels:cwise_op; 973s
    [Sched] @org_tensorflow//tensorflow/core/kernels:cwise_op; 972s
    [Sched] Compiling external/org_tensorflow/.../xla/service/backend.cc; 971s
    [Sched] @org_tensorflow//tensorflow/core/kernels:cwise_op; 966s
    [Sched] @org_tensorflow//tensorflow/core/kernels:cwise_op; 966s
    [Sched] @org_tensorflow//tensorflow/core/kernels:cwise_op; 953s


Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analysed target //tensorflow_serving/model_servers:tensorflow_model_server (192 packages loaded, 15036 targets configured).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/org_tensorflow/tensorflow/core/kernels/BUILD:3882:1: C++ compilation of rule '@org_tensorflow//tensorflow/core/kernels:cwise_op' failed (Exit 4): gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/execroot/tf_serving && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/core/kernels/_objs/cwise_op/cwise_op_mul_1.d '-frandom-seed=bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/core/kernels/_objs/cwise_op/cwise_op_mul_1.o' -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DEIGEN_HAS_TYPE_TRAITS=0' -DTF_USE_SNAPPY -DCURL_STATICLIB -DPLATFORM_LINUX -DENABLE_CURL_CLIENT -DENABLE_NO_ENCRYPTION -iquote external/org_tensorflow -iquote bazel-out/k8-opt/genfiles/external/org_tensorflow -iquote bazel-out/k8-opt/bin/external/org_tensorflow -iquote external/com_google_absl -iquote bazel-out/k8-opt/genfiles/external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -iquote external/nsync -iquote bazel-out/k8-opt/genfiles/external/nsync -iquote bazel-out/k8-opt/bin/external/nsync -iquote external/eigen_archive -iquote bazel-out/k8-opt/genfiles/external/eigen_archive -iquote bazel-out/k8-opt/bin/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/k8-opt/genfiles/external/local_config_sycl -iquote bazel-out/k8-opt/bin/external/local_config_sycl -iquote external/com_googlesource_code_re2 -iquote bazel-out/k8-opt/genfiles/external/com_googlesource_code_re2 -iquote bazel-out/k8-opt/bin/external/com_googlesource_code_re2 -iquote external/gif -iquote bazel-out/k8-opt/genfiles/external/gif -iquote bazel-out/k8-opt/bin/external/gif -iquote external/libjpeg_turbo -iquote bazel-out/k8-opt/genfiles/external/libjpeg_turbo -iquote bazel-out/k8-opt/bin/external/libjpeg_turbo -iquote external/com_google_protobuf -iquote bazel-out/k8-opt/genfiles/external/com_google_protobuf -iquote bazel-out/k8-opt/bin/external/com_google_protobuf -iquote external/zlib_archive -iquote bazel-out/k8-opt/genfiles/external/zlib_archive -iquote bazel-out/k8-opt/bin/external/zlib_archive -iquote external/farmhash_archive -iquote bazel-out/k8-opt/genfiles/external/farmhash_archive -iquote bazel-out/k8-opt/bin/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/k8-opt/genfiles/external/fft2d -iquote bazel-out/k8-opt/bin/external/fft2d -iquote external/highwayhash -iquote bazel-out/k8-opt/genfiles/external/highwayhash -iquote bazel-out/k8-opt/bin/external/highwayhash -iquote external/double_conversion -iquote bazel-out/k8-opt/genfiles/external/double_conversion -iquote bazel-out/k8-opt/bin/external/double_conversion -iquote external/snappy -iquote bazel-out/k8-opt/genfiles/external/snappy -iquote bazel-out/k8-opt/bin/external/snappy -iquote external/hwloc -iquote bazel-out/k8-opt/genfiles/external/hwloc -iquote bazel-out/k8-opt/bin/external/hwloc -iquote external/curl -iquote bazel-out/k8-opt/genfiles/external/curl -iquote bazel-out/k8-opt/bin/external/curl -iquote external/boringssl -iquote bazel-out/k8-opt/genfiles/external/boringssl -iquote bazel-out/k8-opt/bin/external/boringssl -iquote external/jsoncpp_git -iquote bazel-out/k8-opt/genfiles/external/jsoncpp_git -iquote bazel-out/k8-opt/bin/external/jsoncpp_git -iquote external/aws -iquote bazel-out/k8-opt/genfiles/external/aws -iquote bazel-out/k8-opt/bin/external/aws -isystem external/nsync/public -isystem bazel-out/k8-opt/genfiles/external/nsync/public -isystem bazel-out/k8-opt/bin/external/nsync/public -isystem external/eigen_archive -isystem bazel-out/k8-opt/genfiles/external/eigen_archive -isystem bazel-out/k8-opt/bin/external/eigen_archive -isystem external/gif -isystem bazel-out/k8-opt/genfiles/external/gif -isystem bazel-out/k8-opt/bin/external/gif -isystem external/com_google_protobuf/src -isystem bazel-out/k8-opt/genfiles/external/com_google_protobuf/src -isystem bazel-out/k8-opt/bin/external/com_google_protobuf/src -isystem external/zlib_archive -isystem bazel-out/k8-opt/genfiles/external/zlib_archive -isystem bazel-out/k8-opt/bin/external/zlib_archive -isystem external/farmhash_archive/src -isystem bazel-out/k8-opt/genfiles/external/farmhash_archive/src -isystem bazel-out/k8-opt/bin/external/farmhash_archive/src -isystem external/double_conversion -isystem bazel-out/k8-opt/genfiles/external/double_conversion -isystem bazel-out/k8-opt/bin/external/double_conversion -isystem external/hwloc/hwloc -isystem bazel-out/k8-opt/genfiles/external/hwloc/hwloc -isystem bazel-out/k8-opt/bin/external/hwloc/hwloc -isystem external/hwloc/include -isystem bazel-out/k8-opt/genfiles/external/hwloc/include -isystem bazel-out/k8-opt/bin/external/hwloc/include -isystem external/curl/include -isystem bazel-out/k8-opt/genfiles/external/curl/include -isystem bazel-out/k8-opt/bin/external/curl/include -isystem external/boringssl/src/include -isystem bazel-out/k8-opt/genfiles/external/boringssl/src/include -isystem bazel-out/k8-opt/bin/external/boringssl/src/include -isystem external/jsoncpp_git/include -isystem bazel-out/k8-opt/genfiles/external/jsoncpp_git/include -isystem bazel-out/k8-opt/bin/external/jsoncpp_git/include -isystem external/aws/aws-cpp-sdk-core/include -isystem bazel-out/k8-opt/genfiles/external/aws/aws-cpp-sdk-core/include -isystem bazel-out/k8-opt/bin/external/aws/aws-cpp-sdk-core/include -isystem external/aws/aws-cpp-sdk-s3/include -isystem bazel-out/k8-opt/genfiles/external/aws/aws-cpp-sdk-s3/include -isystem bazel-out/k8-opt/bin/external/aws/aws-cpp-sdk-s3/include -mavx -mavx2 -mfma -msse4.1 -msse4.2 '-std=c++14' '-D_GLIBCXX_USE_CXX11_ABI=0' '-D_GLIBCXX_USE_CXX11_ABI=0' -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare '-ftemplate-depth=900' -fno-exceptions -msse3 -DTENSORFLOW_MONOLITHIC_BUILD -pthread -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/org_tensorflow/tensorflow/core/kernels/cwise_op_mul_1.cc -o bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/core/kernels/_objs/cwise_op/cwise_op_mul_1.o)
Execution platform: @bazel_tools//platforms:host_platform
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Target //tensorflow_serving/model_servers:tensorflow_model_server failed to build
INFO: Elapsed time: 3412.116s, Critical Path: 2050.49s
INFO: 3012 processes: 3012 local.
FAILED: Build did NOT complete successfully

```

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Osx 10.14.6, 2.4 GHz Intel Core i9, 32 GB 2400 MHz DDR4
- **TensorFlow Serving installed from (source or binary)**: source
- **TensorFlow Serving version**: 2.1.0

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in
TensorFlow Serving.

cant build the tf serving devel image

### Exact Steps to Reproduce
Please include all steps necessary for someone to reproduce this issue on their
own machine. If not, skip this section.

here are the steps to build it:
```
USER=geri
TAG=2.1.0
TF_SERVING_VERSION_GIT_BRANCH="2.1.0"

docker login --username=$USER --password-stdin

git clone --branch="${TF_SERVING_VERSION_GIT_BRANCH}" https://github.com/tensorflow/serving

TF_SERVING_BUILD_OPTIONS="--copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-msse4.1 --copt=-msse4.2 --jobs=1 --local_resources=8192,2.0,1.0"

cd serving && \
  docker build --pull -t $USER/tensorflow-serving-devel:$TAG \
  --build-arg TF_SERVING_VERSION_GIT_BRANCH="${TF_SERVING_VERSION_GIT_BRANCH}" \
  --build-arg TF_SERVING_BUILD_OPTIONS="${TF_SERVING_BUILD_OPTIONS}" \
  -f tensorflow_serving/tools/docker/Dockerfile.devel .
```

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached. Try to provide a reproducible test case that is the bare
minimum necessary to generate the problem.

**Comment by gowthamkpr** [comment]
What version of bazel are you using to build serving?

**Comment by geraldstanje** [comment]
@gowthamkpr whatever is here in the image: https://github.com/tensorflow/serving/blob/d83512c6b5b2b8433df2fd61bbbfb22e0295b3d3/tensorflow_serving/tools/docker/Dockerfile.devel

**Comment by taruntandon88** [comment]
Getting the same error on the r.15 branch as well (I'm running docker on a Mac machine).
`ERROR: /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/org_tensorflow/tensorflow/core/kernels/BUILD:4321:1: C++ compilation of rule '@org_tensorflow//tensorflow/core/kernels:conv_ops' failed (Exit 4)
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,`

**Comment by geraldstanje** [comment]
i fixed my error. i gave the docker desktop the following settings on osx:
- number of cpus: 8
- memory: 16GB
- swap: 2GB

i used the following compile options:
```--local_resources=8192,2.0,1.0```

@taruntandon88 can you try the same?

**Comment by christisg** [comment]
The following commit should fix the issue: https://github.com/tensorflow/serving/commit/b9602b3820dddea0d9fa9423b1ae9eaaf2aec977#diff-1faa52ce24cf571c7aa9182dbd63b266.

**Comment by geraldstanje** [comment]
@christisg i used commit from master master branch (b9602b3), but it still was failing - so i guess thats not helping?

**Comment by taruntandon88** [comment]
@geraldstanje , I was able to proceed by using 
`--local_resources=8192,2.0,1.0`
Thanks for the help.

I got the following issue in the later stage. I'm adding more space to the docker disk image to try getting past this error.
`Error processing tar file(exit status 1): write /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/execroot/tf_serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/cc/ops/lookup_ops_gen_cc: no space left on device`

**Comment by christisg** [comment]
@geraldstanje could you confirm you're still experiencing the problem?

**Comment by geraldstanje** [comment]
no, we can close it thanks.
