### ISSUE TITLE
The following signatures were invalid: EXPKEYSIG 544B7F63BF9E4D5F

### ISSUE THREAD

**Issue by thijstriemstra** [tensorflow/serving#1896]
Doing apt-get update results in this error message:

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used.
GPG error: http://storage.googleapis.com/tensorflow-serving-apt stable InRelease: The following signatures were invalid: 
EXPKEYSIG 544B7F63BF9E4D5F Tensorflow Serving Developer (Tensorflow Serving APT repository key) <tensorflow-serving-dev@googlegroups.com>
```

**Comment by sushrutikhar** [comment]
I am facing the same error too

**Comment by anuragtr** [comment]
facing the same issue, unable to install tensorflow-serving.

**Comment by Swapnillader21** [comment]
facing the same issue, unable to install tensorflow-serving tried curl with new key as well

**Comment by kev216** [comment]
the same issue.
![Capture d’écran 2021-07-19 à 15 41 53](https://user-images.githubusercontent.com/763429/126169208-e3f2f491-ce3e-4b8e-8f26-68b23ccee8fd.png)

**Comment by fdonnangelo** [comment]
Also facing the same issue !

**Comment by lilao** [comment]
This should be fixed now. Please retry. Thanks!

**Comment by LKNSI** [comment]
Sorry to reopen, but this needs to be executed to update the keys on your own machine. Or you can just wait for them to be refreshed (i honestly don't know when that happens).

```shell
apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 544B7F63BF9E4D5F
```

**Comment by JamesHWade** [comment]
I see the not that this should be fixed, but I'm still seeing that error.

**Comment by AlexBlack2202** [comment]
> This should be fixed now. Please retry. Thanks!

I have this issues right now. I think this error was not fixed.

**Comment by fhaque** [comment]
We have a similar issue where we are using Artifactory Remote Repository and we get a bad signature error.

**Comment by vincentmele** [comment]
For those that are looking to fix this, you need to download the latest public gpg key and add it again. For Debian/Ubuntu:
`wget https://storage.googleapis.com/tensorflow-serving-apt/tensorflow-serving.release.pub.gpg`
`sudo apt-key add tensorflow-serving.release.pub.gpg`
`sudo apt-get update`

**Comment by evanlin1995** [comment]
followed the above steps to download the key, it looks like it may have expired again:
```
# apt-key list
/etc/apt/trusted.gpg
--------------------
pub   rsa4096 2017-07-13 [SC] [expired: 2022-07-19]
      916E 2B2F EBC2 7493 0BAC  A9D9 544B 7F63 BF9E 4D5F
uid           [ expired] Tensorflow Serving Developer (Tensorflow Serving APT repository key) <tensorflow-serving-dev@googlegroups.com>

/etc/apt/trusted.gpg.d/ubuntu-keyring-2012-archive.gpg
------------------------------------------------------
```

**Comment by LazaMeli2022** [comment]
Hi, i having this issue again (https://github.com/tensorflow/serving/issues/1896). Please, can you help me?

**Comment by trams** [comment]
I think the key expired again
```
apt-key list
```
gives

```
pub   rsa4096 2017-07-13 [SC] [expired: 2024-07-31]
      916E 2B2F EBC2 7493 0BAC  A9D9 544B 7F63 BF9E 4D5F
uid           [ expired] Tensorflow Serving Developer (Tensorflow Serving APT repository key) <tensorflow-serving-dev@googlegroups.com>
```

And it has been a year or so since this ticket has been closed

**Comment by trams** [comment]
I guess someone already reported https://github.com/tensorflow/serving/issues/2247

**Comment by trams** [comment]
And this happens again :) I guess 1 year passed
